server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://106.15.72.234:3306/crm_vue?serverTimezone=UTC
    username: root
    password: 981204
mybatis:
  type-aliases-package: com.hziee.pojo

