server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///crm_vue?serverTimezone=UTC
    username: root
    password: 981204
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.hziee.pojo

